import csv
import json
import urllib.request, urllib.parse, urllib.error


f = open('조리식품의 레시피 DB.csv', 'w', encoding='utf-8-sig', newline='')
wr = csv.writer(f)

data_type = [
            "RCP_SEQ",
            "RCP_NM",
            "RCP_WAY2",
            "RCP_PAT2",
            "INFO_WGT",
            "INFO_ENG",
            "INFO_CAR",
            "INFO_PRO",
            "INFO_FAT",
            "INFO_NA",
            "HASH_TAG",
            "ATT_FILE_NO_MAIN",
            "ATT_FILE_NO_MK",
            "RCP_PARTS_DTLS",
            "MANUAL01",
            "MANUAL_IMG01",
            "MANUAL02",
            "MANUAL_IMG02",
            "MANUAL03",
            "MANUAL_IMG03",
            "MANUAL04",
            "MANUAL_IMG04",
            "MANUAL05",
            "MANUAL_IMG05",
            "MANUAL06",
            "MANUAL_IMG06",
            "MANUAL07",
            "MANUAL_IMG07",
            "MANUAL08",
            "MANUAL_IMG08",
            "MANUAL09",
            "MANUAL_IMG09",
            "MANUAL10",
            "MANUAL_IMG10",
            "MANUAL11",
            "MANUAL_IMG11",
            "MANUAL12",
            "MANUAL_IMG12",
            "MANUAL13",
            "MANUAL_IMG13",
            "MANUAL14",
            "MANUAL_IMG14",
            "MANUAL15",
            "MANUAL_IMG15",
            "MANUAL16",
            "MANUAL_IMG16",
            "MANUAL17",
            "MANUAL_IMG17",
            "MANUAL18",
            "MANUAL_IMG18",
            "MANUAL19",
            "MANUAL_IMG19",
            "MANUAL20",
            "MANUAL_IMG20",
            ]

wr.writerow(data_type)

#########################################################

url = "http://openapi.foodsafetykorea.go.kr/api/d9c714fad5b143629fac/COOKRCP01/json/1/1000"
uh = urllib.request.urlopen(url)
barcode_data = uh.read().decode()
json_data = (json.loads(barcode_data))['COOKRCP01']['row']

for i in range(0, 1000):
    product = [json_data[i]["RCP_SEQ"],
            json_data[i]["RCP_NM"],
            json_data[i]["RCP_WAY2"],
            json_data[i]["RCP_PAT2"],
            json_data[i]["INFO_WGT"],
            json_data[i]["INFO_ENG"],
            json_data[i]["INFO_CAR"],
            json_data[i]["INFO_PRO"],
            json_data[i]["INFO_FAT"],
            json_data[i]["INFO_NA"],
            json_data[i]["HASH_TAG"],
            json_data[i]["ATT_FILE_NO_MAIN"],
            json_data[i]["ATT_FILE_NO_MK"],
            json_data[i]["RCP_PARTS_DTLS"],
            json_data[i]["MANUAL01"],
            json_data[i]["MANUAL_IMG01"],
            json_data[i]["MANUAL02"],
            json_data[i]["MANUAL_IMG02"],
            json_data[i]["MANUAL03"],
            json_data[i]["MANUAL_IMG03"],
            json_data[i]["MANUAL04"],
            json_data[i]["MANUAL_IMG04"],
            json_data[i]["MANUAL05"],
            json_data[i]["MANUAL_IMG05"],
            json_data[i]["MANUAL06"],
            json_data[i]["MANUAL_IMG06"],
            json_data[i]["MANUAL07"],
            json_data[i]["MANUAL_IMG07"],
            json_data[i]["MANUAL08"],
            json_data[i]["MANUAL_IMG08"],
            json_data[i]["MANUAL09"],
            json_data[i]["MANUAL_IMG09"],
            json_data[i]["MANUAL10"],
            json_data[i]["MANUAL_IMG10"],
            json_data[i]["MANUAL11"],
            json_data[i]["MANUAL_IMG11"],
            json_data[i]["MANUAL12"],
            json_data[i]["MANUAL_IMG12"],
            json_data[i]["MANUAL13"],
            json_data[i]["MANUAL_IMG13"],
            json_data[i]["MANUAL14"],
            json_data[i]["MANUAL_IMG14"],
            json_data[i]["MANUAL15"],
            json_data[i]["MANUAL_IMG15"],
            json_data[i]["MANUAL16"],
            json_data[i]["MANUAL_IMG16"],
            json_data[i]["MANUAL17"],
            json_data[i]["MANUAL_IMG17"],
            json_data[i]["MANUAL18"],
            json_data[i]["MANUAL_IMG18"],
            json_data[i]["MANUAL19"],
            json_data[i]["MANUAL_IMG19"],
            json_data[i]["MANUAL20"],
            json_data[i]["MANUAL_IMG20"]]
    wr.writerow(product)


url = "http://openapi.foodsafetykorea.go.kr/api/d9c714fad5b143629fac/COOKRCP01/json/1001/1308"
uh = urllib.request.urlopen(url)
barcode_data = uh.read().decode()
json_data = (json.loads(barcode_data))['COOKRCP01']['row']

for i in range(0, 308):
    product = [json_data[i]["RCP_SEQ"],
            json_data[i]["RCP_NM"],
            json_data[i]["RCP_WAY2"],
            json_data[i]["RCP_PAT2"],
            json_data[i]["INFO_WGT"],
            json_data[i]["INFO_ENG"],
            json_data[i]["INFO_CAR"],
            json_data[i]["INFO_PRO"],
            json_data[i]["INFO_FAT"],
            json_data[i]["INFO_NA"],
            json_data[i]["HASH_TAG"],
            json_data[i]["ATT_FILE_NO_MAIN"],
            json_data[i]["ATT_FILE_NO_MK"],
            json_data[i]["RCP_PARTS_DTLS"],
            json_data[i]["MANUAL01"],
            json_data[i]["MANUAL_IMG01"],
            json_data[i]["MANUAL02"],
            json_data[i]["MANUAL_IMG02"],
            json_data[i]["MANUAL03"],
            json_data[i]["MANUAL_IMG03"],
            json_data[i]["MANUAL04"],
            json_data[i]["MANUAL_IMG04"],
            json_data[i]["MANUAL05"],
            json_data[i]["MANUAL_IMG05"],
            json_data[i]["MANUAL06"],
            json_data[i]["MANUAL_IMG06"],
            json_data[i]["MANUAL07"],
            json_data[i]["MANUAL_IMG07"],
            json_data[i]["MANUAL08"],
            json_data[i]["MANUAL_IMG08"],
            json_data[i]["MANUAL09"],
            json_data[i]["MANUAL_IMG09"],
            json_data[i]["MANUAL10"],
            json_data[i]["MANUAL_IMG10"],
            json_data[i]["MANUAL11"],
            json_data[i]["MANUAL_IMG11"],
            json_data[i]["MANUAL12"],
            json_data[i]["MANUAL_IMG12"],
            json_data[i]["MANUAL13"],
            json_data[i]["MANUAL_IMG13"],
            json_data[i]["MANUAL14"],
            json_data[i]["MANUAL_IMG14"],
            json_data[i]["MANUAL15"],
            json_data[i]["MANUAL_IMG15"],
            json_data[i]["MANUAL16"],
            json_data[i]["MANUAL_IMG16"],
            json_data[i]["MANUAL17"],
            json_data[i]["MANUAL_IMG17"],
            json_data[i]["MANUAL18"],
            json_data[i]["MANUAL_IMG18"],
            json_data[i]["MANUAL19"],
            json_data[i]["MANUAL_IMG19"],
            json_data[i]["MANUAL20"],
            json_data[i]["MANUAL_IMG20"]]
    wr.writerow(product)


f.close()